#!/usr/bin/env python3
"""PreToolUse guard for Bash. Denies pushes, history rewrites, AI attribution, and shell
writes to locked paths."""
import json, re, sys

try:
    cmd = (json.load(sys.stdin).get("tool_input") or {}).get("command", "")
except Exception:
    sys.exit(0)
DENY = [
    (r"\bgit\s+push\b", "git push is reserved for the user"),
    (r"--amend\b|\bgit\s+rebase\b|\bgit\s+filter-|\bgit\s+reset\s+--hard|--no-verify\b", "no history rewriting"),
    (r"Co-Authored-By|Generated with Claude|generated by Claude", "no AI attribution in this repo"),
    (r"\bgit\s+config\s+(--global\s+)?user\.", "do not change git identity"),
    (r"CLAUDE_CODE_STOP_HOOK_BLOCK_CAP|stop-blocks", "do not tamper with the stop gate"),
    (r"(\brm\b|\bmv\b|\bcp\b|\btee\b|\bsed\s+-i|\btruncate\b|\bchmod\b|>{1,2})[^|;&]*"
     r"(projects/|site/verify\.py|site/shoot\.py|site/review\.py|site/review/|site/snapshots|\.claude/|RUBRIC\.md|NOTICE\.md)",
     "shell write to a locked path"),
    (r"\bgit\s+(rm|checkout|restore)\b[^|;&]*(projects/|site/snapshots|\.claude/|site/verify\.py|site/shoot\.py|site/review)",
     "git write to a locked path"),
    (r"python3?\s+-c\s+.*open\(.*(projects/|snapshots|verify\.py|\.claude)", "inline python write to a locked path"),
]
for pat, why in DENY:
    if re.search(pat, cmd, re.S):
        print(f"DENIED: {why}. Command: {cmd[:200]}", file=sys.stderr)
        sys.exit(2)
sys.exit(0)
