#!/usr/bin/env python3
"""PreToolUse guard for Edit/Write. Denies writes to frozen evidence, the grader, the
hooks, and generated output. Reads the tool call as JSON on stdin."""
import json, os, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PROTECTED = ["projects/", "docs/", "site/verify.py", "site/shoot.py", "site/review.py",
             "site/review/", "site/snapshots/", ".claude/", "NOTICE.md", "LICENSE"]
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)
path = (data.get("tool_input") or {}).get("file_path") or (data.get("tool_input") or {}).get("notebook_path") or ""
if not path:
    sys.exit(0)
p = Path(os.path.expanduser(path))
if not p.is_absolute():
    p = ROOT / p
try:
    relp = str(p.resolve().relative_to(ROOT))
except ValueError:
    relp = str(p.resolve())
hit = next((x for x in PROTECTED if relp == x.rstrip("/") or relp.startswith(x) or x in relp), None)
if hit:
    print(f"DENIED: {relp} is protected ({hit}). projects/ is frozen evidence; docs/ is generated by "
          f"site/build.py (edit site/templates, site/static, site/data instead); the grader, "
          f"snapshots and hooks are locked. Do not try to work around this.", file=sys.stderr)
    sys.exit(2)
sys.exit(0)
